spring.application.name=MotorVallarta

# Nivel de log global
logging.level.root=INFO

# Nivel de log para tu paquete
logging.level.com.tde.motorVallarta=DEBUG

# Guardar en archivo
logging.file.name=logs/vallarta.log

# Máximo tamaño y número de archivos (opcional)
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=10
