server:
 port: 8087
spring:
  datasource:
   
    
    #Desarrollo 
    origin:
      jdbc-url: jdbc:sqlserver://131.1.0.129:1433;databaseName=Vallarta;encrypt=true;trustServerCertificate=true
      username: sa
      password: sa
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      
    
    destination:
      jdbc-url: jdbc:sqlserver://131.1.0.93;databaseName=INTELIBUS;encrypt=true;trustServerCertificate=true
      username: sa
      password: sa
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 
    

  jpa:
   
   properties:
    hibernate:
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
    show-sql: true
  hibernate:
    ddl-auto: none  # Ajusta según lo que necesites